### ISSUE TITLE
翻訳作業の管理用チェックリスト / Translation Progress Checklist

### ISSUE THREAD

**Issue by meganetaaan** [Moddable-OpenSource/moddable-jp#3]
進捗管理用のissueです。新しいドキュメントを翻訳する際は **最初にこのissueで宣言をお願いします**。作業に重複が合った場合は、原則としてissueで先に宣言した方を優先します。

翻訳作業の進め方については[README](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/translation_readme.md)を確認してください。

- リポジトリトップ
  - [x] [/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/readme.md)
  - [x] [/contributing.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributing.md)
  - [x] [/translation_readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/translation_readme.md)
- licenses
  - [x] [/licenses/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/licenses/readme.md)
- documentation
  - [x] [/documentation/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/readme.md)
  - [x] [/documentation/Moddable%20SDK%20-%20Getting%20Started.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/Moddable%20SDK%20-%20Getting%20Started.md)
- documentation/モジュール群
  - [x] [/documentation/files/files.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/files/files.md)
  - [ ] [/documentation/io/firmata.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/io/firmata.md)
  - [x] [/documentation/io/io.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/io/io.md)
  - [x] [/documentation/crypt/crypt.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/crypt/crypt.md)
  - [ ] [/documentation/piu/die-cut.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/die-cut.md)
  - [x] [/documentation/piu/localization.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/localization.md)
  - [x] [/documentation/piu/piu.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/piu.md)
  - [x] [/documentation/piu/ae%20motion%20export.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/ae%20motion%20export.md)
  - [x] [/documentation/piu/expanding-keyboard.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/expanding-keyboard.md)
  - [x] [/documentation/piu/keyboard.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/keyboard.md)
  - [ ] [/documentation/network/securesocket.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/securesocket.md)
  - [ ] [/documentation/network/ble/ble.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/ble/ble.md)
  - [ ] [/documentation/network/ethernet.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/ethernet.md)
  - [ ] [/documentation/network/webthings.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/webthings.md)
  - [ ] [/documentation/network/network.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/network.md)
  - [x] [/documentation/drivers/ili9341/ili9341.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/ili9341/ili9341.md)
  - [x] [/documentation/drivers/ls013b4dn04/ls013b4dn04.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/ls013b4dn04/ls013b4dn04.md)
  - [x] [/documentation/drivers/lpm013m126a/lpm013m126a.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/lpm013m126a/lpm013m126a.md)
  - [x] [/documentation/drivers/st7735/st7735.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/st7735/st7735.md)
  - [x] [/documentation/drivers/destm32s/destm32s.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/destm32s/destm32s.md)
  - [x] [/documentation/drivers/MCP230XX/MCP230XX.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/MCP230XX/MCP230XX.md)
  - [x] [/documentation/drivers/dotstar/dotstar.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/dotstar/dotstar.md)
  - [x] [/documentation/drivers/ssd1351/ssd1351.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/ssd1351/ssd1351.md)
  - [x] [/documentation/drivers/neostrand/neostrand.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/neostrand/neostrand.md)
  - [x] [/documentation/drivers/ssd1306/ssd1306.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/drivers/ssd1306/ssd1306.md)
  - [x] [/documentation/tools/testing.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/tools/testing.md)
  - [x] [/documentation/tools/manifest.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/tools/manifest.md)
  - [x] [/documentation/tools/tools.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/tools/tools.md)
  - [x] [/documentation/tools/defines.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/tools/defines.md)
  - [x] [/documentation/base/setup.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/base/setup.md)
  - [x] [/documentation/base/worker.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/base/worker.md)
  - [x] [/documentation/base/base.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/base/base.md)
  - [x] [/documentation/data/data.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/data/data.md)
  - [x] [/documentation/commodetto/Creating%20fonts%20for%20Moddable%20applications.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/commodetto/Creating%20fonts%20for%20Moddable%20applications.md)
  - [ ] [/documentation/commodetto/commodetto.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/commodetto/commodetto.md)
  - [x] [/documentation/commodetto/poco.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/commodetto/poco.md)
  - [x] [/documentation/commodetto/outline/Outlines.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/commodetto/outline/Outlines.md)
  - [x] [/documentation/pins/audioout.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/pins/audioout.md)
  - [x] [/documentation/pins/pins.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/pins/pins.md)
- documentation/xs
  - [x] [/documentation/xs/preload.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/preload.md)
  - [x] [/documentation/xs/mods.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/mods.md)
  - [ ] [/documentation/xs/xst.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/xst.md)
  - [ ] [/documentation/xs/XS%20Platforms.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20Platforms.md)
  - [x] [/documentation/xs/xsbug.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/xsbug.md)
  - [ ] [/documentation/xs/ROM%20Colors.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/ROM%20Colors.md)
  - [ ] [/documentation/xs/handle.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/handle.md)
  - [ ] [/documentation/xs/XS%20Marshalling.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20Marshalling.md)
  - [x] [/documentation/xs/XS%20Differences.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20Differences.md)
  - [ ] [/documentation/xs/XS%20Compartment.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20Compartment.md)
  - [ ] [/documentation/xs/XS%20Profiler.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20Profiler.md)
  - [ ] [/documentation/xs/XS%20in%20C.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20in%20C.md)
  - [ ] [/documentation/xs/XS%20linker%20warnings.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20linker%20warnings.md)
  - [ ] [/documentation/xs/XS%20Conformance.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20Conformance.md)
  - [ ] [/documentation/xs/XS%20Scopes.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/xs/XS%20Scopes.md)
- documentation/devices
  - [x] [/documentation/devices/moddable-two.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/moddable-two.md)
  - [ ] [/documentation/devices/qca4020/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/qca4020/README.md)
  - [x] [/documentation/devices/esp32.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/esp32.md)
  - [ ] [/documentation/devices/gecko/GeckoBuild.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/gecko/GeckoBuild.md)
  - [x] [/documentation/devices/m5paper.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/m5paper.md)
  - [x] [/documentation/devices/moddable-one.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/moddable-one.md)
  - [x] [/documentation/devices/moddable-three.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/moddable-three.md)
  - [x] [/documentation/devices/m5core_ink.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/m5core_ink.md)
  - [x] [/documentation/devices/moddable-display.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/moddable-display.md)
  - [x] [/documentation/devices/moddable-zero.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/moddable-zero.md)
  - [x] [/documentation/devices/pico.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/pico.md)
  - [x] [/documentation/devices/wasm.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/wasm.md)
  - [x] [/documentation/devices/esp8266.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/esp8266.md)
  - [ ] [/documentation/devices/nRF52-low-power.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/nRF52-low-power.md)
  - [x] [/documentation/devices/nrf52.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/nrf52.md)
  - [x] [/documentation/devices/moddable-four.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/moddable-four.md)
  - [x] [/documentation/devices/moddable-six.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/moddable-six.md)
- documentation/displays
  - [x] [/documentation/displays/wiring-guide-generic-2.4-spi-pico.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-generic-2.4-spi-pico.md)
  - [x] [/documentation/displays/wiring-guide-adafruit-OLED.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-adafruit-OLED.md)
  - [x] [/documentation/displays/wiring-guide-switch-science-LCD.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-switch-science-LCD.md)
  - [x] [/documentation/displays/wiring-guide-crystalfontz-eink.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-crystalfontz-eink.md)
  - [x] [/documentation/displays/wiring-guide-generic-2.4-spi.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-generic-2.4-spi.md)
  - [x] [/documentation/displays/wiring-guide-sparkFun-teensyview-spi.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-sparkFun-teensyview-spi.md)
  - [x] [/documentation/displays/wiring-guide-sharp-memory-1.3-spi.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-sharp-memory-1.3-spi.md)
  - [x] [/documentation/displays/wiring-guide-generic-1.44-spi.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-generic-1.44-spi.md)
  - [x] [/documentation/displays/wiring-guide-generic-2.8-CPT-spi.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-generic-2.8-CPT-spi.md)
  - [x] [/documentation/displays/wiring-guide-dotstar.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-dotstar.md)
  - [x] [/documentation/displays/wiring-guide-sharp-memory-2.7-spi.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-sharp-memory-2.7-spi.md)
  - [x] [/documentation/displays/wiring-guide-generic-2.4-spi-esp32.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-generic-2.4-spi-esp32.md)
  - [x] [/documentation/displays/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/readme.md)
  - [x] [/documentation/displays/wiring-guide-adafruit-1.8-st7735.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/displays/wiring-guide-adafruit-1.8-st7735.md)
- examples
  - [x] [/examples/io/tcp/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/io/tcp/readme.md)
  - [x] [/examples/io/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/io/readme.md)
  - [x] [/examples/io/streams/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/io/streams/readme.md)
  - [x] [/examples/piu/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/piu/readme.md)
  - [x] [/examples/piu/round-bme68x/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/piu/round-bme68x/readme.md)
  - [x] [/examples/network/aws/moddable-aws-guide.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/network/aws/moddable-aws-guide.md)
  - [x] [/examples/drivers/sensors/hc-sr04/multiple-sensors/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/drivers/sensors/hc-sr04/multiple-sensors/readme.md)
  - [x] [/examples/drivers/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/drivers/readme.md)
  - [x] [/examples/drivers/peripherals/rtc/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/drivers/peripherals/rtc/readme.md)
  - [x] [/examples/js/compartments/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/js/compartments/readme.md)
  - [x] [/examples/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/readme.md)
  - [x] [/examples/commodetto/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/commodetto/readme.md)
  - [x] [/examples/pins/audioout/http-stream/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/pins/audioout/http-stream/readme.md)
  - [x] [/examples/packages/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/packages/readme.md)
- modules
  - [x] [/modules/io/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/io/readme.md)
  - [x] [/modules/drivers/sensors/ft6206/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/drivers/sensors/ft6206/readme.md)
  - [x] [/modules/drivers/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/drivers/readme.md)
  - [x] [/modules/data/mp3/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/data/mp3/readme.md)
  - [x] [/modules/commodetto/gif/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/commodetto/gif/readme.md)
- build
  - [ ] [/build/devices/nrf52/examples/clearpeers/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/build/devices/nrf52/examples/clearpeers/readme.md)
  - [ ] [/build/devices/nrf52/examples/BLE_DFU/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/build/devices/nrf52/examples/BLE_DFU/readme.md)
- contributed
  - [ ] [/contributed/giphy/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/giphy/readme.md)
  - [ ] [/contributed/ble/hid-peripheral/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/ble/hid-peripheral/README.md)
  - [ ] [/contributed/effects/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/effects/readme.md)
  - [ ] [/contributed/httpbridge/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/httpbridge/README.md)
  - [ ] [/contributed/window-display-moddable-one/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/window-display-moddable-one/readme.md)
  - [ ] [/contributed/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/README.md)
  - [ ] [/contributed/charlieplexer/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/charlieplexer/README.md)
  - [ ] [/contributed/modClock/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/modClock/readme.md)
  - [ ] [/contributed/jsonparser/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/README.md)
  - [ ] [/contributed/jsonparser/examples/cookbook/sample-schedule-info-app/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/cookbook/sample-schedule-info-app/README.md)
  - [ ] [/contributed/jsonparser/examples/cookbook/sample-weather-app/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/cookbook/sample-weather-app/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/builder/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/builder/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/tracer/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/tracer/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/escape/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/escape/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/tree/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/tree/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/schedule/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/schedule/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/basic/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/basic/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/matcher/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/matcher/README.md)
  - [ ] [/contributed/jsonparser/examples/reference/pattern/README.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/jsonparser/examples/reference/pattern/README.md)
  - [ ] [/contributed/serial/SerialModule.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/serial/SerialModule.md)
  - [ ] [/contributed/serial/drivers/sim7100/SIM7100.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/contributed/serial/drivers/sim7100/SIM7100.md)

**Comment by stc1988** [comment]
*  /contributing.md
*  /documentation/Moddable SDK - Getting Started.md
上記２つを着手します

**Comment by meganetaaan** [comment]
/contributing.md マージ完了 https://github.com/Moddable-OpenSource/moddable-jp/pull/8

**Comment by stc1988** [comment]
contributingの流れで以下着手します
 * /licenses/readme.md

**Comment by ronron-gh** [comment]
とりあえず、そこそこ使ったことがあるものからやってみます
 - /documentation/piu/piu.md

**Comment by stc1988** [comment]
着手する人が増えたので、少し多めに予約しておきます
* /documentation/readme.md
*  /documentation/tools/manifest.md
* /documentation/tools/tools.md
* /documentation/tools/defines.md

**Comment by meganetaaan** [comment]
下記着手します。
来週の発表でIOモジュールとECMA-419の紹介をしたい。

- /documentation/io/io.md
-  /modules/io/readme.md
-  /examples/io/readme.md
-  /examples/io/tcp/readme.md
-  /examples/io/streams/readme.md

**Comment by stc1988** [comment]
* /documentation/tools/testing.md
優先度高くなかったのですが、`/documentation/tools` まとめてで対応します

**Comment by stc1988** [comment]
GW明けからはペースも落ちるので、prはファイル単位で出していきます
* /documentation/xs/preload.md
* /documentation/xs/mods.md
* /documentation/xs/xsbug.md

**Comment by stc1988** [comment]
上記完了見込みがでてきたので次を
* /documentation/devices/esp32.md
* /documentation/devices/pico.md
* /documentation/commodetto/Creating fonts for Moddable applications.md
* /documentation/base/setup.md
* /examples/readme.md

**Comment by meganetaaan** [comment]
`/documentation/tools` マージ完了 https://github.com/Moddable-OpenSource/moddable-jp/pull/15

**Comment by meganetaaan** [comment]
`documentation/readme.md` マージ完了 #14

**Comment by meganetaaan** [comment]
`/licenses/readme.md` https://github.com/Moddable-OpenSource/moddable-jp/pull/11
`documentaion/Moddable SDK - Getting Started.md` #13
マージ完了

**Comment by stc1988** [comment]
以下着手します

* /documentation/pins/audioout.md
* /documentation/pins/pins.md

**Comment by stc1988** [comment]
以下着手します
* /documentation/base/worker.md
* /documentation/base/base.md
* /documentation/data/data.md
* /documentation/crypt/crypt.md

**Comment by stc1988** [comment]
以下着手します
* examples/packages/readme.md
* modules/commodetto/gif/readme.md
* modules/data/mp3/readme.md

**Comment by tenugui-taro** [comment]
こんにちは、Moddable 日本語翻訳プロジェクトに参加させていただきたいです！（CLA は提出済みです。）

手始めに Moddable の学習で読んだことのある下記ファイルに取り組もうと思います、よろしくお願いします！
-  /documentation/xs/XS Differences.md

**Comment by tenugui-taro** [comment]
次は下記ファイルの翻訳に取り組みます！
-  /documentation/commodetto/poco.md

**Comment by stc1988** [comment]
以下着手します
* /documentation/devices/moddable-two.md
* /documentation/devices/m5paper.md
* /documentation/devices/moddable-one.md
* /documentation/devices/moddable-three.md
* /documentation/devices/m5core_ink.md
* /documentation/devices/moddable-display.md
* /documentation/devices/moddable-zero.md
* /documentation/devices/moddable-four.md

**Comment by ronron-gh** [comment]
> とりあえず、そこそこ使ったことがあるものからやってみます
> 
>     * /documentation/piu/piu.md

宣言してから時間が経ってしまったので、進捗を報告します。現在20%くらいです（内容が多いページなので時間がかかっていますが少しずつ進めています）

**Comment by stc1988** [comment]
documentation/displays　以下をまとめて着手します

**Comment by stc1988** [comment]
以下着手します。

*  /documentation/piu/localization.md
*  /documentation/drivers/neostrand/neostrand.md
*  /documentation/devices/moddable-six.md
*  /examples/pins/audioout/http-stream/readme.md
*  ~~/examples/packages/readme.md~~ 翻訳済みでした

**Comment by stc1988** [comment]
以下`/examples`の残を着手します。

* /examples/piu/readme.md
* /examples/piu/round-bme68x/readme.md
* /examples/network/aws/moddable-aws-guide.md
* /examples/drivers/sensors/hc-sr04/multiple-sensors/readme.md
* /examples/drivers/readme.md
* /examples/drivers/peripherals/rtc/readme.md
* /examples/js/compartments/readme.md
* /examples/commodetto/readme.md

**Comment by tenugui-taro** [comment]
下記ファイルの翻訳に取り組みます！
- /documentation/commodetto/outline/Outlines.md

**Comment by meganetaaan** [comment]
リストの各項目にドキュメントへのリンクを貼りました。翻訳有無のチェックにお使いください。
メインブランチ（`dev/translate-jp`）の最新を指すようになってます。

**Comment by stc1988** [comment]
以下着手します

* [/modules/drivers/sensors/ft6206/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/drivers/sensors/ft6206/readme.md)
*  [/modules/drivers/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/drivers/readme.md)
* [/documentation/piu/ae%20motion%20export.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/ae%20motion%20export.md)
*  [/documentation/piu/expanding-keyboard.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/expanding-keyboard.md)
*  [/documentation/piu/keyboard.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/piu/keyboard.md)

**Comment by stc1988** [comment]
`/documentation/drivers`配下を着手します

**Comment by stc1988** [comment]
以下着手します
* [/documentation/network/securesocket.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/securesocket.md)
* [/documentation/network/ethernet.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/ethernet.md)
* [/documentation/network/network.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/network/network.md)

**Comment by stc1988** [comment]
@meganetaaan 
以下翻訳済みですので、チェック欄更新お願いします
- [/documentation/commodetto/outline/Outlines.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/commodetto/outline/Outlines.md)
- [/documentation/devices/m5paper.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/documentation/devices/m5paper.md)
- [/examples/piu/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/piu/readme.md)
- [/examples/piu/round-bme68x/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/piu/round-bme68x/readme.md)
- [/examples/network/aws/moddable-aws-guide.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/network/aws/moddable-aws-guide.md)
- [/examples/js/compartments/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/js/compartments/readme.md)
- [/examples/commodetto/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/examples/commodetto/readme.md)
- [/modules/drivers/sensors/ft6206/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/drivers/sensors/ft6206/readme.md)
- [/modules/drivers/readme.md](https://github.com/moddable-OpenSource/moddable-jp/blob/dev/translate-jp/modules/drivers/readme.md)

**Comment by stc1988** [comment]
documentation/commodetto/commodetto.md

着手します

**Comment by stc1988** [comment]
/documentation/network/ble/ble.md
着手します

**Comment by stc1988** [comment]
documentation/network/ble/ble.md
着手します。主要モジュールはこれで完了かも

**Comment by meganetaaan** [comment]
後出しですみません。下記翻訳してPR作りました。 https://github.com/Moddable-OpenSource/moddable-jp/pull/60

[XS Conformance.md](https://github.com/Moddable-OpenSource/moddable-jp/pull/60/files#diff-c0454888c107761491c3c669be17530461ef85ef7e2ffdd58a277c1effcd9c26)
[XS Platforms.md](https://github.com/Moddable-OpenSource/moddable-jp/pull/60/files#diff-7b925325790daf6299bce42f7aaa542df62694a5cd10ba5019360ebd2d5e7714)
[XS Profiler.md](https://github.com/Moddable-OpenSource/moddable-jp/pull/60/files#diff-969768c7a58d20e4d15eaee9061b0a9153c7c34d28593f89bbf465b377ba3b38)
[XS in C.md](https://github.com/Moddable-OpenSource/moddable-jp/pull/60/files#diff-95b9c9dd8b0216e8e28feccb4ac6f53be53be87d8db063f61a24ca26fde5f2d5)
[handle.md](https://github.com/Moddable-OpenSource/moddable-jp/pull/60/files#diff-d5caa73457ec9112eeee053ca30df597183c080aa6f84df6a8301b20292fc847)
[xst.md](https://github.com/Moddable-OpenSource/moddable-jp/pull/60/files#diff-16fd3d2779c99869e4c80126927bdd88ef67fed589902b02512829c4ed2ca354)
